fun 
()  {
try {}
catch (e: OK) {
         "Unexpected exception: $!!::class"
    }()
}
